apiVersion: 1

datasources:
  - name: MySQL Dummy Device
    type: mysql
    url: mysql-db:3306
    database: openiot
    user: root
    password: 123
    secureJsonData:
      password: 123

  - name: MySQL Mocked Device
    type: mysql
    url: mysql-db:3306
    database: smartpower_mock
    user: root
    password: 123
    secureJsonData:
      password: 123